### ISSUE TITLE
Reuse apps

### ISSUE THREAD

**Issue by ranma42** [di-unipi-socc/microset#3]
Several basic blocks (such as `backend` and `frontend`) could be reused.
To ensure that it is possible and easy, they should not contain "counters" (example: if `frontend1` is meant to be the same as `frontend`, drop the `1`).

**Comment by lucarin91** [comment]
ok, fell free to change the names

**Comment by jsoldani** [comment]
SIDE COMMENT:

In the case of "extensibility", frontend1 and frontend2 should be actually different. This is because frontend2 adds a new functionality to the microservice-based app.

**Comment by lucarin91** [comment]
Actually, `frontend`, `frontend1`, and `frontend2`, and also `backend`, `backend1`, and `backend2` are different implementation of similar service. Indeed, each one either returns different values or has a different interface. 

We can instead try to create a base frontend and backend service and then extends them to create the components of the application.
